export const FETCH_COMPANY = 'FETCH_COMPANY' 
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS'
export const FETCH_COMPANY_FAILURE = 'FETCH_COMPANY_FAILURE'

export const FETCH_COMPANY_NEWS = 'FETCH_COMPANY_NEWS'
export const FETCH_COMPANY_NEWS_SUCCESS = 'FETCH_COMPANY_NEWS_SUCCESS'
export const FETCH_COMPANY_NEWS_FAILURE = 'FETCH_COMPANY_NEWS_FAILURE'